#spring.application.name=ZoomGoBackEnd

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test01
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

application:
  jwt:
    secretKey: d1e7de6c6976969fb2ff10df6ac9d782a897fa9893af8da675be368d9e2b3561
    expiration: 900000 # 15분 access token
    refreshExpiration: 864000000 # 1일 refresh token