#spring.application.name=ZoomGoBackEnd

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test01
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    logging:
      level:
        org:
          hibernate:
            SQL: debug
            type: trace