#spring.application.name=ZoomGoBackEnd

server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "qhdrhaos258@gmail.com"
    password: "xiey umph zcuq akia"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?
  datasource:
    url: jdbc:mysql://localhost:3306/bootex
    username: bootuser
    password: Bootuser123!@#
    diverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    logging:
      level:
        org:
          hibernate:
            SQL: debug
            type: trace