#spring.application.name=zoomgobackend
spring:
  datasource:
    diverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test01
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true